# Site settings
title: Yarkcy's
email: yarkcy@gmail.com
description: "Good good study, day day up!"
baseurl: ""
url: "http://yarkcy.com"
twitter_username: yarkcy
github_username:  yarkcy

# Build settings
markdown: kramdown
permalink: pretty
